kind: pipeline
name: default


steps:
  - name: linter
    image: snakepacker/python:all
    commands:
      - tox
    environment:
      TOXENV: lint
    when:
      event:
        - push

  - name: python 3.5
    image: snakepacker/python:all
    commands:
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py35
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      event:
        - pull_request

  - name: python 3.6
    image: snakepacker/python:all
    commands:
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      event:
        - pull_request

  - name: python 3.7
    image: snakepacker/python:all
    commands:
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      event:
        - pull_request

  - name: test all
    image: snakepacker/python:all
    commands:
      - tox
      - coveralls
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST
      username:
        from_secret: SMTP_USERNAME
      password:
        from_secret: SMTP_PASSWORD
      from:
        from_secret: SMTP_USERNAME
      when:
        status:
          - changed
          - failure
    when:
      event:
        exclude:
          - pull_request
          - push


services:
  - name: rabbitmq
    image: rabbitmq:3-alpine
    when:
      event:
        exclude:
          - push
