kind: pipeline
name: default


steps:
  - name: python 3.5
    image: snakepacker/python:all
    commands:
      - pip3.5 install pylava
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py35

  - name: python 3.6
    image: snakepacker/python:all
    commands:
      - pip3.6 install pylava
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py36

  - name: python 3.7
    image: snakepacker/python:all
    commands:
      - pip3.7 install pylava
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py37

services:
  - name: rabbitmq
    image: rabbitmq:3-alpine
