---
kind: pipeline
name: default


steps:
  - name: linter
    image: snakepacker/python:all
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      TOXENV: lint

  - name: mypy
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      TOXENV: mypy

  - name: checkdoc
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      TOXENV: checkdoc

  - name: python 3.8
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py38
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.8 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py38-uvloop
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.7
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.7 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py37-uvloop
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.6
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.6 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py36-uvloop
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.5
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py35
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.5 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    commands:
      - wait-for-port rabbitmq:5672
      - tox
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq
      TOXENV: py35-uvloop
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

services:
  - name: rabbitmq
    image: rabbitmq:3-alpine
---
kind: signature
hmac: b08a61b3eb2e1b32a313778123cc46e0982b264acf09f3717b43b9d2ed0663b0

...
